### ISSUE TITLE
直接部署：报错收集静态资源失败。 docker部署：容器内log ‘启动服务失败’。请教一下解决方法。

### ISSUE THREAD

**Issue by gojuukaze** [gojuukaze/liteAuth#7]
直接部署：报错收集静态资源失败。 docker部署：容器内log ‘启动服务失败’。请教一下解决方法。

_Originally posted by @GithubElijah in https://github.com/gojuukaze/liteAuth/issues/2#issuecomment-1149382178_

**Comment by gojuukaze** [comment]
@GithubElijah

直接部署你可以直接在安装目录运行下面命令，看看报错信息
```
python3 manage.py collectstatic
```

至于doker的话正常应该是不会启动失败的，看看是不是目录权限问题，或者贴一下完整的日志吗

**Comment by GithubElijah** [comment]
谢谢大佬，docke部署问题已解决，原因是-v 映射的配置文件可能没写好导致起不来。解决方式：取消-v，等容器起来了去容器里vim创建config，再restart container就欧克了。

**Comment by gojuukaze** [comment]
配置文件不对应该不会影响docker运行，另外-v不建议取消，不然一旦docker容器被意外删除数据就没了

**Comment by GithubElijah** [comment]
再次请教，confluence 配置 liteauth，该如何配置呢？ ou和dc怎么填呢？

**Comment by gojuukaze** [comment]
为空或者任意值都行（如：ou=user），liteauth会自动忽略 ou和dc两项  

具体的配置说明可以看这个：https://doc.ikaze.cn/liteauth/ldap/index.html
